version: '3.8'
services: 
    client: 
        stdin_open: true
        tty: true
        build: 
            context: ./client
            dockerfile: Dockerfile
        volumes: 
            - /client/node_modules
            - ./client:/client
        ports: 
            - "3000:3000"
    server:
        build: 
            context: ./server
            dockerfile: Dockerfile
        volumes: 
            - /server/node_modules
            - ./server:/server
        ports: 
            - "4000:4000"
        env_file: 
            - ./server/.env
        depends_on:
            - mysql
    mysql:
        image: mysql:latest
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: qwerty123
            MYSQL_DATABASE: deltaexchange
        volumes:
            - ./mysql_data:/var/lib/mysql
    nginx:
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        depends_on: 
            - client
            - server
        restart: always
        ports: 
            - "5000:80"